# Generated by Django 4.2.20 on 2025-04-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_usermode_delete_sensordata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMode',
        ),
    ]
